<style>
    .letterName {
        text-align: center;
    }
    .Rectangle-Copy-3 {
        width: 160px;
        height: 2px;
        border-radius: 1px;
        background-color: #ececec;
        margin:0 38% 0 38%;
    }
    .Active-text-label-Copy-4 {
        width: 142px;
        height: 24px;
        font-family: OpenSansHebrew;
        font-size: 18px;
        font-weight: bold;
        font-stretch: normal;
        font-style: normal;
        line-height: normal;
        letter-spacing: normal;
        text-align: center;
        color: #000b40;
    }
    .Label-Text {

        opacity: 0.6;
        font-family: OpenSansHebrew;
        font-size: 14px;
        font-weight: normal;
        font-stretch: normal;
        font-style: normal;
        line-height: 1.8;
        letter-spacing: normal;
        text-align: right;
        color: #1e2132;
        margin-left:<?php echo $langDir === "rtl"?'100px':'0'?>;
        margin-right:<?php echo $langDir === "rtl"?'0':'100px'?>;
        vertical-align: top;
    }
    }
    .Input-text {
        font-family: OpenSansHebrew;
        font-size: 16px;
        font-weight: normal;
        font-stretch: normal;
        font-style: normal;
        line-height: 1.5;
        letter-spacing: normal;
        text-align: right;
        color: #000b40;
        margin-left:<?php echo $langDir === "rtl"?'100px':'0'?>;
        margin-right:<?php echo $langDir === "rtl"?'0':'100px'?>;

    }
    .position_content{
    <?php echo $langDir==="rtl"?'margin-left:34%;':''?>;
    <?php echo $langDir!=="rtl"?'margin-right:34%;':''?>;
    }
    .tdLabel{
        min-width: 20%;
        max-width: 20%;

    .tdContext{

        min-width:30%;
        max-width:30%;
        word-wrap: break-word;
        overflow-wrap: break-word;

    }
    .position{
        position:absolute;
        margin-left:<?php echo $langDir==="rtl"?'0':'70%'?>;
        margin-right:<?php echo $langDir==="rtl"?'70%':'0'?>;
    }
    .RectangleThree {
    <?php echo $langDir==="rtl"?'margin-left:1%;':''?>;
    <?php echo $langDir!=="rtl"?'margin-right:1%;':''?>;
        width: 98%;
        border:1px solid gray;
        padding:3px;
    }

    .LableTableBody-text-3 {
        font-family: OpenSansHebrew;
        font-size: 12px;
        color: #000b40;
        width: (100/8)%;
        vertical-align: top;
        margin-right:0 20px 0 20px;
        width:20%;
    }
    .LableTableBody-text-9 {
        font-family: OpenSansHebrew;
        font-size: 12px;
        color: #000b40;
        width: (100/8)%;
        vertical-align: top;
        margin-right:0 20px 0 20px;
        width:80%;
    }
    
</style>
<?php
function dateDifference($date_1 , $date_2 , $differenceFormat = '%d' )
{
    $datetime1 = date_create($date_1);
    $datetime2 = date_create($date_2);

    $interval = date_diff($datetime1, $datetime2);

    return $interval->format($differenceFormat);

};
?>
<main>
    <?php if ($clientReqData['name_of_letter'] && $clientReqData['name_of_letter']!==""):?>
    <div class="letterName" dir="<?php echo text($langDir); ?>" lang="<?php echo text($langCode); ?>">
        <br/>
        <span class="Active-text-label-Copy-4 "><?php echo xl($clientReqData['name_of_letter']);?> </span>
        <br/>
        <p  class ="Rectangle-Copy-3">  </p>
        <br/>
    </div>
    <?php endif;?>
    <?php
            $patientData["langDir"]=$langDir;
            $patientData["langCode"]=$langCode;
            echo $this->render('clinikal-api/pdf/patient-details.phtml',$patientData);
    ?>
    <br/>
    <br/>
    <?php foreach($bodyData['prescription'] as $medicine):?>
    <table   class="RectangleThree position_content" dir="<?php echo text($langDir); ?>" lang="<?php echo text($langCode); ?>">
        <tbody>
            <tr>
                <td class=" LableTableBody-text-3"><?php echo xl("Drug name");?></td> <td class=" LableTableBody-text-9"><?php echo $medicine['drug'];?></td>
            </tr>
            <tr>
                <td class=" LableTableBody-text-3"><?php echo xl("Quantity");?></td> <td class=" LableTableBody-text-9"><?php echo $medicine['dosage']." ".xl($bodyData['forms'][$medicine['form']]);?> </td>
            </tr>
            <tr><?php $period =   str_replace("$", dateDifference($medicine['end_date'],$medicine['start_date']),xl("In Duration of $ Days"));?>
            <tr><?php $route =   $langDir=="ltr" ? "1 ".xl($bodyData['form'][$medicine['form']])." ".xl($bodyData['route'][$medicine['route']]): xl($bodyData['form'][$medicine['form']])." 1 ". xl($bodyData['route'][$medicine['route']]);?>
                <td class=" LableTableBody-text-3"><?php echo xl("Instructions for use");?></td> <td class=" LableTableBody-text-9"><?php echo $route." ,". $medicine['interval']." ".xl("A day")." (".$period.") ";?></td>
            </tr>
            <tr>
                <td class=" LableTableBody-text-3"><?php echo xl("Instructions");?></td> <td class=" LableTableBody-text-9"><?php echo $medicine['note'];?></td>
            </tr>

        </tbody>
    </table>
    <br/>
    <?php endforeach;?>

    <br/>
    <br/>
    <div style="page-break-inside:avoid;" >
        <?php
        $doctorData["langDir"]=$langDir;
        $doctorData["langCode"]=$langCode;
        echo $this->render('clinikal-api/pdf/doctor-signature.phtml',$doctorData);
        ?>
    </div>
</main>
