<style>
    .leftO{
        float:left;
        text-align:left;
    }
    .letterName {
        text-align: center;
    }
    .Rectangle-Copy-3 {
        width: 160px;
        height: 2px;
        border-radius: 1px;
        background-color: #ececec;
        margin:0 38% 0 38%;
    }
    .Active-text-label-Copy-4 {
        width: 142px;
        height: 24px;
        font-family: OpenSansHebrew;
        font-size: 18px;
        font-weight: bold;
        font-stretch: normal;
        font-style: normal;
        line-height: normal;
        letter-spacing: normal;
        text-align: center;
        color: #000b40;
    }
    .Label-Text {

        font-family: OpenSansHebrew;
        font-size: 14px;
        font-weight: normal;
        font-stretch: normal;
        font-style: normal;
        line-height: 1.8;
        letter-spacing: normal;
        text-align: <?php echo $langDir === "rtl"?'right':'left'?>;
        color: #1e2132;
        vertical-align: top;
    }

    .LabelInput-text {
        font-family: OpenSansHebrew;
        font-size: 12px;
        font-weight: normal;
        font-stretch: normal;
        font-style: normal;
        line-height: 1.5;
        letter-spacing: normal;
        text-align: center;
        color: #000b40;
        vertical-align: top;


    }
    .Input-text {
        font-family: OpenSansHebrew;
        font-size: 16px;
        font-weight: normal;
        font-stretch: normal;
        font-style: normal;
        line-height: 1.5;
        letter-spacing: normal;
        text-align: right;
        color: #000b40;
        vertical-align: top;

    }

    .tdLabel{
        min-width: 20%;
        max-width: 20%;
    }

    .tdContext{

        min-width:30%;
        max-width:30%;
        word-wrap: break-word;
        overflow-wrap: break-word;


    }


    .LabeTableHeader-text {
        font-family: OpenSansHebrew;
        font-size: 10px;
        color: dimgrey;
        width: (100/8)%;
        vertical-align: top;
    }
    .LableTableBody-text {
        font-family: OpenSansHebrew;
        font-size: 12px;
        color: #000b40;
        width: (100/8)%;
        vertical-align: top;
    }
    .RectangleTwo {
    <?php echo $langDir==="rtl"?'margin-left:1%;':''?>;
    <?php echo $langDir!=="rtl"?'margin-right:1%;':''?>;
    width: 98%;
    }
</style>
<main>
    <?php if ($clientReqData['name_of_letter'] && $clientReqData['name_of_letter']!==""):?>
    <div class="letterName" dir="<?php echo text($langDir); ?>" lang="<?php echo text($langCode); ?>">
        <br/>
        <span class="Active-text-label-Copy-4 "><?php echo xl($clientReqData['name_of_letter']);?> </span>
        <br/>
        <p  class ="Rectangle-Copy-3">  </p>
        <br/>
    </div>

    <?php endif;?>
    <?php
            $patientData["langDir"]=$langDir;
            $patientData["langCode"]=$langCode;
            echo $this->render('clinikal-api/pdf/patient-details.phtml',$patientData);
    ?>
    <br/>
    <br/>
    <table     class="RectangleTwo position_content" dir="<?php echo text($langDir); ?>" lang="<?php echo text($langCode); ?>">
    <tbody>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Reason for refferal");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['reason_for_refferal']) ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Detail");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['reason_for_refferal_details']) ;?>
        </td>
    </tr>
    <tr> <td class="tdLabel Label-Text">
            <?php echo xl("Insulation");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['insulation']=="1"?"Yes":"No") ;?>
        </td>
    </tr>
    <tr> <td class="tdLabel Label-Text">
            <?php echo xl("Insulation instruction");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['insulation_instructions']) ;?>
        </td>
    </tr>
    <tr> <td class="tdLabel Label-Text">
            <?php echo xl("Nursing anamnesis");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['nursing_anamnesis']) ;?>
        </td>
    </tr>
    <tr> <td class="tdLabel Label-Text">
            <?php echo xl("Pregnancy");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['pregnant']) ;?>
        </td>
    </tr>
    <tr> <td class="tdLabel Label-Text">
            <?php echo xl("Sensitivities");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['sensitivities']) ;?>
        </td>
    </tr>
    <tr> <td class="tdLabel Label-Text">
            <?php echo xl("Background diseases");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['background_diseases']) ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Chronic medications");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['chronic_medications']) ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text"><?php echo xl("Constant indicators");?></td>
        <td class="tdContext Input-text"><?php echo $bodyData['constants_indicators']['columns']['height']; ?> - <?php echo $bodyData['constants_indicators']['rows'][0]['height'][2];?> <?php echo $bodyData['constants_indicators']['rows'][0]['height'][1];?></td>
    </tr>

    <tr>
        <td class="tdLabel Label-Text"></td>
        <td class="tdContext Input-text"><?php echo $bodyData['constants_indicators']['columns']['weight']; ?> - <?php echo $bodyData['constants_indicators']['rows'][0]['weight'][2];?> <?php echo $bodyData['constants_indicators']['rows'][0]['weight'][1];?></td>
    </tr>

    </tr>


    <tr>
        <td class="tdLabel Label-Text"><?php echo xl("Variable indicators");?></td>
        <td class="tdContext ">
            <table  style="page-break-inside:avoid; " class="RectangleTwo position_content">
                <tr>
                    <?php foreach($bodyData['variable_indicators']['columns'] as $column):?>
                        <th class="LabeTableHeader-text"> <?php echo $column;?></th>
                    <?php endforeach;?>
                </tr>
                <tr>
                    <?php foreach($bodyData['variable_indicators']['rows'] as $row):?>
                        <tr >

                            <?php foreach($row as $k=>$col):?>
                            <td  dir="ltr">
                                <center ><span class="LableTableBody-text">
                                    <?php switch($k):
                                    case "date":?>
                                        <?php echo $col[1];?>
                                        <?php break;?>
                                    <?php case "oxygen_saturation" :?>
                                        <?php echo $col[2] !="-" ? $col[2].$col[1] : $col[2];?>
                                        <?php break;?>
                                    <?php default:?>
                                        <?php echo $col[2];?>

                                    <?php endswitch;?>
                                <?php endforeach;?>
                                        </span>
                                </center>
                            </td>
                        </tr>
                <?php endforeach;?>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text"><?php echo xl("Tests and treatments performed");?></td>
        <td>
            <?php foreach($bodyData['service_requests'] as $sericeReq):?>
            <table  style="page-break-inside:avoid; ">
                <tbody>

                    <tr>
                        <td class="Input-text"><?php echo xl("Test/Treatment");?></td>
                        <td class="Input-text"><?php echo xl($sericeReq['tests_and_treatments_title']);?></td>
                    </tr>
                    <?php if($sericeReq['instruction_code']=='x_ray'):?>
                    <tr>
                        <td class="Input-text"><?php echo xl("X-Ray Type");?></td>
                        <td class="Input-text"><?php echo $sericeReq['order_detail_code'];?></td>
                    </tr>
                    <?php elseif($sericeReq['instruction_code']=='details_providing_medicine'):?>
                    <tr>
                        <td class="Input-text"><?php echo xl("Drug name");?></td>
                        <td class="Input-text"><?php echo $sericeReq['order_detail_code'];?></td>
                    </tr>
                    <?php endif;?>
                    <?php if($sericeReq['patient_instruction'] && $sericeReq['patient_instruction']!=""):?>
                    <tr>
                        <td class="Input-text"><?php echo xl("Instructions");?></td>
                        <td class="Input-text"><?php echo $sericeReq['patient_instruction'];?></td>
                    </tr>
                    <?php endif;?>
                    <?php if($sericeReq['note'] && $sericeReq['note']!=""):?>
                    <tr>
                        <td class="Input-text"><?php echo xl("Remark");?></td>
                        <td class="Input-text"><?php echo $sericeReq['note'];?></td>
                    </tr>
                    <?php endif;?>


                </tbody>
            </table>
            <br/>
            <?php endforeach;?>
        </td>
    </tr>

    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Findings");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo $bodyData['findings'] ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Diagnosis");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo $bodyData['diagnostics'] ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Treatment details");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo $bodyData['treatment_details'] ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Recommendations on release");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo $bodyData['recommendations_on_release'] ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Recommendations for medications");?>
        </td>
        <td dir='ltr'  class="leftO tdContext Input-text">
            <ul>
                <?php foreach( $bodyData['recommendations_for_medications'] as $drug):?>
                    <li   ><?php echo $drug['drug'];?></li>
                <?php endforeach;?>
            </ul>
        </td>
    </tr>

    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Decision on release");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['decision_on_release']);?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Release date");?>
        </td>
    <td>
        <table>
            <tbody>

    <tr>

        <td  dir='ltr' class="tdContext Input-text">
            <?php echo xl("Date") ;?>
        </td>
        <td  dir='ltr' class="tdContext Input-text">
            <?php echo $bodyData['release_date']['day'] ;?>
        </td>
    </tr>
    <tr>

        <td  dir='ltr' class="tdContext Input-text">
            <?php echo xl("Hour") ;?>
        </td>
        <td  dir='ltr' class="tdContext Input-text">
            <?php echo $bodyData['release_date']['hour'] ;?>
        </td>
    </tr>

            </tbody>
        </table>
    </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Evacuation way");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo xl($bodyData['evacuation_way']) ;?>
        </td>
    </tr>
    <tr>
        <td class="tdLabel Label-Text">
            <?php echo xl("Sick leave");?>
        </td>
        <td class="tdContext Input-text">
            <?php echo $bodyData['sick_leave']. " ". xl("Days") ;?>
        </td>
    </tr>
    </tbody>
    </table>
    <div style="page-break-inside:avoid;" >
    <?php
            $doctorData["langDir"]=$langDir;
            $doctorData["langCode"]=$langCode;
            echo $this->render('clinikal-api/pdf/doctor-signature.phtml',$doctorData);
    ?>
    </div>

</main>

