<?php echo $header; ?>

<?php echo $this->$helper($data); ?>

<style>

</style>

<script>

    let filterInitialInfo;

    function goToPatientFile(event){
        let pid=event.target.getAttribute("data");
        topatient(pid);
        return 1;
    }

    //set number of records in data table
    pageLength=50;

    $(document).ready(function(){

        $('#startFilter').off()
            .on('click',function() {
                    $(".dataTable").DataTable().ajax.reload();
                }
            );

        $("#filter_action").removeClass('col-md-1').addClass("col-md-2")
        filterInitialInfo=collectFilters();
        let hideAdvanced=false;
    });

</script>
