
-- list of statements
DELETE FROM  list_options WHERE list_id = 'clinikal_templates';
INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`, `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`, `activity`, `subtype`, `edit_options`) VALUES
('clinikal_templates', '1', 'טקסט 1 לשדה אנמנזה סיעודית בהתייבשות', 1, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '2', 'טקסט 2 לשדה אנמנזה סיעודית בהתייבשות', 2, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '6', 'טקסט 1 לשדה אנמנזה סיעודית בחבלת ראש', 6, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '7', 'טקסט 2 לשדה אנמנזה סיעודית בחבלת ראש', 7, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '50', 'טקסט 1 לשדה הנחיות לצילום רנטגן התייבשות', 50, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '51', 'טקסט 2 לשדה הנחיות לצילום רנטגן התייבשות', 51, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '52', 'טקסט 1 לשדה הנחיות לצילום רנטגן חבלת ראש', 52, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '53', 'טקסט 2 לשדה הנחיות לצילום רנטגן חבלת ראש', 53, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '100', 'טקסט 1 לשדה הנחיות למתן תרופה בהתייבשות', 100, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '101', 'טקסט 2 לשדה הנחיות למתן תרופה בהתייבשות', 101, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '105', 'טקסט 1 לשדה הנחיות למתן תרופה חבלת ראש', 105, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '106', 'טקסט 2 לשדה הנחיות למתן תרופה חבלת ראש', 106, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '150', 'טקסט 1 לשדה הנחיות בהתייבשות', 150, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '151', 'טקסט 2 לשדה הנחיות בהתייבשות', 151, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '155', 'טקסט 1 לשדה הנחיות בחבלת ראש', 155, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '156', 'טקסט 1 לשדה הנחיות בחבלת ראש', 156, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '200', 'טקסט 1 לשדה פירוט הממצאים בהתייבשות', 200, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '201', 'טקסט 2 לשדה פירוט הממצאים בהתייבשות', 201, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '205', 'טקסט 1 לשדה פירוט הממצאים חבלת ראש', 205, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '206', 'טקסט 2 לשדה פירוט הממצאים חבלת ראש', 206, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '250', 'טקסט 1 לשדה פירוט האבחנה בהתייבשות', 250, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '251', 'טקסט 2 לשדה פירוט האבחנה בהתייבשות', 251, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '255', 'טקסט 1 לשדה פירוט האבחנה חבלת ראש', 255, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '256', 'טקסט 2 לשדה פירוט האבחנה חבלת ראש', 256, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '300', 'טקסט 1 לשדה פירוט הטיפול שניתן בהתייבשות', 300, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '301', 'טקסט 2 לשדה פירוט הטיפול שניתן בהתייבשות', 301, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '305', 'טקסט 1 לשדה פירוט הטיפול שניתן חבלת ראש', 305, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '306', 'טקסט 2 לשדה פירוט הטיפול שניתן חבלת ראש', 306, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '350', 'טקסט 1 לשדה הוראות להמשך טיפול בהתייבשות', 350, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '351', 'טקסט 2 לשדה הוראות להמשך טיפול בהתייבשות', 351, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '355', 'טקסט 1 לשדה הוראות להמשך טיפול חבלת ראש', 355, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '356', 'טקסט 2 לשדה הוראות להמשך טיפול חבלת ראש', 356, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '400', 'יש לקחת עם האוכל', 400, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '401', 'יש לקחת על כשעה לפני האוכל', 401, 0, 0, '', '', '', 0, 0, 1, '', 1),
('clinikal_templates', '402', 'יש להימנע מחשיפה לשמש', 402, 0, 0, '', '', '', 0, 0, 1, '', 1);


DELETE FROM  clinikal_templates_map;

INSERT INTO `clinikal_templates_map` (`form_id`, `form_field`, `service_type`, `reason_code`, `message_id`, `seq`) VALUES
('medical_admission', 'nursing_anamnesis ', '1', '1', '1', 1),
('medical_admission', 'nursing_anamnesis ', '1', '1', '2', 2),
('medical_admission', 'nursing_anamnesis ', '1', '3', '6', 6),
('medical_admission', 'nursing_anamnesis ', '1', '3', '7', 7),
('tests_and_treatments ', 'templates_x_ray ', '1', '1', '50', 50),
('tests_and_treatments ', 'templates_x_ray ', '1', '1', '51', 51),
('tests_and_treatments ', 'templates_x_ray ', '1', '3', '52', 52),
('tests_and_treatments ', 'templates_x_ray ', '1', '3', '53', 53),
('tests_and_treatments ', 'templates_providing_medicine ', '1', '1', '100', 100),
('tests_and_treatments ', 'templates_providing_medicine ', '1', '1', '101', 101),
('tests_and_treatments ', 'templates_providing_medicine ', '1', '3', '105', 105),
('tests_and_treatments ', 'templates_providing_medicine ', '1', '3', '106', 106),
('tests_and_treatments ', 'templates_laboratory_tests ', '1', '1', '150', 150),
('tests_and_treatments ', 'templates_laboratory_tests ', '1', '1', '151', 151),
('tests_and_treatments ', 'templates_laboratory_tests ', '1', '3', '155', 155),
('tests_and_treatments ', 'templates_laboratory_tests ', '1', '3', '156', 156),
('diagnosis_and_recommendations', 'findings_details', '1', '1', '200', 200),
('diagnosis_and_recommendations', 'findings_details', '1', '1', '201', 201),
('diagnosis_and_recommendations', 'findings_details', '1', '3', '205', 205),
('diagnosis_and_recommendations', 'findings_details', '1', '3', '206', 206),
('diagnosis_and_recommendations', 'diagnosis_details', '1', '1', '250', 250),
('diagnosis_and_recommendations', 'diagnosis_details', '1', '1', '251', 251),
('diagnosis_and_recommendations', 'diagnosis_details', '1', '3', '255', 255),
('diagnosis_and_recommendations', 'diagnosis_details', '1', '3', '256', 256),
('diagnosis_and_recommendations', 'treatment_details', '1', '1', '300', 300),
('diagnosis_and_recommendations', 'treatment_details', '1', '1', '301', 301),
('diagnosis_and_recommendations', 'treatment_details', '1', '3', '305', 305),
('diagnosis_and_recommendations', 'treatment_details', '1', '3', '306', 306),
('diagnosis_and_recommendations', 'instructions_further_treatment', '1', '1', '350', 350),
('diagnosis_and_recommendations', 'instructions_further_treatment', '1', '1', '351', 351),
('diagnosis_and_recommendations', 'instructions_further_treatment', '1', '3', '355', 355),
('diagnosis_and_recommendations', 'instructions_further_treatment', '1', '3', '356', 356),
('diagnosis_and_recommendations', 'instructions_drug', '1', '1', '400', 400),
('diagnosis_and_recommendations', 'instructions_drug', '1', '1', '401', 401),
('diagnosis_and_recommendations', 'instructions_drug', '1', '3', '402', 402);
